# Codecov configuration
coverage:
  status:
    project:
      default:
        # Adjust these thresholds as needed
        target: 70%  # Overall project coverage target
        threshold: 2%  # Allow coverage to drop by 2% without failing
    patch:
      default:
        # Coverage for new/modified code in PRs
        target: 80%  # New code should have 80% coverage
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false  # Comment even if no coverage change

ignore:
  # Files/folders to exclude from coverage
  - "src/__tests__"
  - "*.test.js"
  - "*.spec.js"
  - "scripts"
  - "data"
  - "chess-analyzer-frontend"  # Frontend tracked separately

flags:
  backend:
    paths:
      - "src/"
    carryforward: true
  frontend:
    paths:
      - "chess-analyzer-frontend/src/"
    carryforward: true